### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by FangChanguwu** [Agnes4m/nonebot_plugin_maimai#2]
Traceback (most recent call last):
  File "F:\Bot\Nonebot\Miruku\bot.py", line 19, in <module>
    nonebot.run()
  File "F:\Bot\Nonebot\Miruku\.venv\lib\site-packages\nonebot\__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "F:\Bot\Nonebot\Miruku\.venv\lib\site-packages\nonebot\drivers\none.py", line 69, in run
    loop = asyncio.get_event_loop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.

**Comment by Agnes4m** [comment]
emmm，从你的报错中看不出来是我插件的问题
