### ISSUE TITLE
发送/help指令时出错

### ISSUE THREAD

**Issue by LsrlYrsc** [Agnes4m/nonebot_plugin_maimai#3]
02-22 16:23:55 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_maimai.public, lineno=58)
02-22 16:23:56 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_maimai.public, lineno=58) running complete02-22 16:23:56 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_maimai.public, lineno=58) failed.Traceback (most recent call last):
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot_plugin_maimai\public.py", line 84, in _
    await help.send(MessageSegment.image(pic))
AttributeError: '_Helper' object has no attribute 'send'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Lsrl\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 817, in simple_run
    await handler(
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Lsrl\mai\.venv\lib\site-packages\nonebot_plugin_maimai\public.py", line 86, in _
    await help.send(help_str)
AttributeError: '_Helper' object has no attribute 'send'

**Comment by Agnes4m** [comment]
已修复
